### PR TITLE
Make installable

### PR DESCRIPTION
**Pull request by jseabold**
Was poking around and noticed this wasn't installable. Tensorflow isn't on PyPI AFAIK, so this will fail if it's not installed but the error message is ok. Might want to add a note to the README. Not sure what you want to put for version and author information.

### CODE REVIEW

**Comment by jseabold** [comment]
The required versions (other than tensorflow) are also wholly arbitrary.

**Comment by geffy** [comment]
Hi!
Thanks for contributing! 
I think it's better to wait for TF 1.0 (hope it will be on PyPI) and after make tffm installable.

**Comment by stared** [comment]
@geffy Now TensorFlow is pip-installable, see: https://www.tensorflow.org/install/.
And I would be excited to see tffm pip-installable as well!

**Comment by geffy** [comment]
Finally, merged :)

**Pull request merged**
